services:
  - type: web
    name: qa-generator
    env: python
    buildCommand: |
      apt-get update && apt-get install -y build-essential swig
      pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13 