services:
  - type: web
    name: qa-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: GROQ_API_KEY
        sync: false  # You'll set this in the Render dashboard
    plan: free 