services:
  - type: web
    name: qa-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GROQ_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true 